"""Create user, goal, plan, and audit tables

Revision ID: 823108182c7d
Revises: 169d80af122b
Create Date: 2026-03-21 13:27:56.952150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823108182c7d'
down_revision: Union[str, Sequence[str], None] = '169d80af122b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.Enum('HOUSE_PURCHASE', 'EMERGENCY_FUND', 'INVESTMENT', 'DEBT_PAYOFF', 'OTHER', name='goaltype'), nullable=False),
    sa.Column('target_amount', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('current_savings', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', name='goalstatus'), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_plan_id'), 'goals', ['plan_id'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('calculation_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('calculation_type', sa.String(length=50), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('calculation_time_ms', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_audits_goal_id'), 'calculation_audits', ['goal_id'], unique=False)
    op.create_index(op.f('ix_calculation_audits_id'), 'calculation_audits', ['id'], unique=False)
    op.create_index(op.f('ix_calculation_audits_input_hash'), 'calculation_audits', ['input_hash'], unique=False)
    op.create_index(op.f('ix_calculation_audits_user_id'), 'calculation_audits', ['user_id'], unique=False)
    op.create_table('financial_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('current_savings', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Integer(), nullable=True),
    sa.Column('monthly_expenses', sa.Integer(), nullable=True),
    sa.Column('current_debt', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_snapshots_goal_id'), 'financial_snapshots', ['goal_id'], unique=False)
    op.create_index(op.f('ix_financial_snapshots_id'), 'financial_snapshots', ['id'], unique=False)
    op.create_table('projection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('is_achievable', sa.Integer(), nullable=False),
    sa.Column('total_months', sa.Integer(), nullable=False),
    sa.Column('final_savings', sa.Integer(), nullable=False),
    sa.Column('final_debt', sa.Integer(), nullable=False),
    sa.Column('final_net_worth', sa.Integer(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=False),
    sa.Column('total_investment_growth', sa.Integer(), nullable=False),
    sa.Column('shortfall_amount', sa.Integer(), nullable=False),
    sa.Column('recommended_monthly_increase', sa.Integer(), nullable=False),
    sa.Column('break_even_month', sa.Integer(), nullable=True),
    sa.Column('monthly_projections', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['calculation_audits.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projection_results_goal_id'), 'projection_results', ['goal_id'], unique=False)
    op.create_index(op.f('ix_projection_results_id'), 'projection_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projection_results_id'), table_name='projection_results')
    op.drop_index(op.f('ix_projection_results_goal_id'), table_name='projection_results')
    op.drop_table('projection_results')
    op.drop_index(op.f('ix_financial_snapshots_id'), table_name='financial_snapshots')
    op.drop_index(op.f('ix_financial_snapshots_goal_id'), table_name='financial_snapshots')
    op.drop_table('financial_snapshots')
    op.drop_index(op.f('ix_calculation_audits_user_id'), table_name='calculation_audits')
    op.drop_index(op.f('ix_calculation_audits_input_hash'), table_name='calculation_audits')
    op.drop_index(op.f('ix_calculation_audits_id'), table_name='calculation_audits')
    op.drop_index(op.f('ix_calculation_audits_goal_id'), table_name='calculation_audits')
    op.drop_table('calculation_audits')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_plan_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
